[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python3",
  "pkg-config",
  "cairo.dev",
  "pango.dev",
  "libjpeg.dev",
  "giflib",
  "librsvg.dev",
  "pixman.dev",
  "glib.dev",
  "fontconfig.dev",
  "freetype.dev",
  "harfbuzz.dev",
]

[phases.build]
cmds = [
  "npm install --omit=dev",
  "bash scripts/rebuild-canvas.sh"
]

[start]
cmd = "node start.js"
